In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier

In [5]:
#Generamos nuestro dataset
uno =np.array([[1,0],[0,1]])
dos =np.array([[1,1],[0,0]])
tres =np.array([[0,0],[1,1]])
cuatro =np.array([[0,1],[1,0]])

In [6]:
uno

array([[1, 0],
       [0, 1]])

In [7]:
uno.shape

(2, 2)

In [16]:
uno = uno.reshape(1,4)

In [17]:
uno = uno.flatten()

In [12]:
dos = dos.flatten()

In [13]:
dos

array([1, 1, 0, 0])

In [14]:
tres = tres.flatten()
cuatro = cuatro.flatten()

In [18]:
X = [uno,dos,tres,cuatro]

In [19]:
X

[array([1, 0, 0, 1]),
 array([1, 1, 0, 0]),
 array([0, 0, 1, 1]),
 array([0, 1, 1, 0])]

In [20]:
X = np.array(X)

In [21]:
X

array([[1, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 1, 0]])

In [22]:
y = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [23]:
y

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [24]:
X[0]

array([1, 0, 0, 1])

In [25]:
y[0]

array([1, 0, 0, 0])

In [31]:
model = MLPClassifier(hidden_layer_sizes = (10,), activation="tanh", max_iter=1000)


In [32]:
model.fit(X,y)

/Users/lfmarin/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='tanh', hidden_layer_sizes=(10,), max_iter=1000)

In [30]:
model.predict(X)

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 0]])

In [33]:
model.predict(X)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])